# Template PHP Build

# This template allows you to validate your PHP application.
# The workflow allows running tests and code linting on the default branch.

image:
  name: *yourimagename*
  username: $DOCKER_HUB_USERNAME
  password: $DOCKER_HUB_PASSWORD

definitions:
  services:
    mysql:
      image: mysql:8.0
      variables:
        MYSQL_DATABASE: app_test
        MYSQL_ROOT_PASSWORD: pass
        MYSQL_USER: app
        MYSQL_PASSWORD: pass

pipelines:
  branches:
    '*':
      - step:
          caches:
            - composer
          name: Test
          script:
            - composer install --optimize-autoloader
            - docker/pipelines/wait-mysql.sh
            - sleep 1
            #- bin/console -e test doctrine:migrations:migrate --no-interaction
            - bin/phpunit
          services:
            - mysql
    master:
      - step:
          caches:
            - composer
          name: Test
          script:
            - composer install --optimize-autoloader
            - docker/pipelines/wait-mysql.sh
            - sleep 1
            #- bin/console -e test doctrine:migrations:migrate --no-interaction
            - bin/phpunit
          services:
            - mysql
      # - step:
      #     caches:
      #       - composer
      #       - docker
      #     name: Deploy image
      #     script:
      #       - touch config/secrets/prod/prod.decrypt.private.php
      #       - echo "<?php return \"$PROD_DECRYPT_KEY\";" > config/secrets/prod/prod.decrypt.private.php
      #       - composer install --no-dev --optimize-autoloader --no-scripts
      #       - composer dump-env prod
      #       - bin/console cache:clear
      #       - docker build -t *yourimagename*-nginx:$BITBUCKET_COMMIT -f docker/Dockerfile_nginx .
      #       - docker build -t *yourimagename*-php:$BITBUCKET_COMMIT -f docker/Dockerfile_php .
      #       - docker login -u$DOCKER_HUB_USERNAME -p$DOCKER_HUB_PASSWORD && docker push *yourimagename*-nginx:$BITBUCKET_COMMIT
      #       - docker login -u$DOCKER_HUB_USERNAME -p$DOCKER_HUB_PASSWORD && docker push *yourimagename*-php:$BITBUCKET_COMMIT
      #     services:
      #       - docker
